files:
  - source: /app/src/main/res/values/moex_strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/moex_strings.xml
    translate_content: 0
    translate_attributes: 0
    content_segmentation: 0
